config/routes.rb
Rails.application.routes.draw do
  get 'tool/pipeline'
  get 'tool/splitter'
  get 'tool/dope'
  get 'tool/refract'
  get 'tool/designer'
  root 'application#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def home 
  end
  def getAPIdata(url, isJSON)
    url = URI(url.to_s)
    # if @@cache.exist?(url.to_s)
    #   p "Loading cache #{url.to_s}"
    #   return @@cache.read(url.to_s)
    # else
      http = Net::HTTP.new(url.host, url.port)  
      request = Net::HTTP::Get.new url.request_uri  
      res = http.request request
      res = res.code == "200" ? (isJSON ? JSON.parse(res.body) : res.body) : -1
      # @@cache.write(url.to_s, res)
      # p "Storing cache #{url.to_s}"
      return res
    # end  
  end
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def system_control
    @files = get_displays()
    @ports = get_ports()
    # render :json => @ports
    render :layout => "full_screen"
  end
  def designer
    @files = get_displays()
    # render :json => @files
    render :layout => "full_screen"
  end
  def index
  	@files = get_displays()
  	render :layout => "full_screen"
  end
  def refract
     render :layout => "full_screen"
  end
  def dope
     render :layout => "full_screen"
  end
  def lens
    @files = get_displays()
    render :layout => "full_screen"
  end
  def theoretical_testbed
    @files = get_displays()
    render :layout => "full_screen"
  end
  def splitter
    @files = get_displays()
    render :layout => "full_screen"
  end
  def optimal_lens
    @files = get_displays()
    render :layout => "full_screen"
  end
  def pipeline
    @files = get_displays()
    render :layout => "full_screen"
  end

  def displays
    @files = get_displays()
    render :json => @files
  end

 def start_server
   # NOTE: currently doesn't work :(
   dir = system('ruby ./ruby_scripts/ArduinoServer.rb &')
   render :json => {msg: "I started server", debug: dir}
 end

 # HELPER METHODS
  def get_displays
    files = {filenames: Dir.glob("public/artwork/*.svg").collect!{|c| c.split('/')[2..-1].join('/')}}
    files[:filenames].collect!{|f| {:collection => f.split('.')[0].split('-')[0].split('_')[0].titlecase, path: "/artwork/", :filename => f, :title => f.split(".")[0].titlecase}}
    
    files2 = {filenames: Dir.glob("public/userstudy/*.svg").collect!{|c| c.split('/')[2..-1].join('/')}}
    files2[:filenames].collect!{|f| {:collection => f.split('.')[0].split('-')[0].split('_')[0].titlecase, path: "/userstudy/", :filename => f, :title => f.split(".")[0].titlecase}}
    
    [files[:filenames], files2[:filenames]].flatten
  end
  def get_ports
    ports = ["/dev/tty.usbmodem*"] #"/dev/tty.HC*", 
    ports.map!{|p| Dir[p]}
    ports.flatten!
  end
end

app/views/application/_flow.html.erb
<style type="text/css">
.btn-group-wrap {
    text-align: center;
}
div.btn-group {
    margin: 0 auto; 
    text-align: center;
    width: inherit;
    display: inline-block;
}

a {
    float: left;   
}
.tesla-links{
	margin: 10px;
}
.tesla-links a em{
	display: block;
	font-size: 0.6em;
}
 .btn-tesla{
	  color: #FFF;
	  background: #5d5d5d;
	}
	.btn-tesla:hover{
	  color: #DDD;
	  text-decoration: none;
	}
	.btn-tesla:visited{
	  color: #FFF;
	  text-decoration: none;
	}

</style>
<div class="btn-group-wrap tesla-links">
<div class="btn-group">
  <%= link_to devices_index_path, :class => "btn btn-lg btn-#{params[:controller] == "devices" ? "primary" : "tesla"}" do%>
   <em> FIND YOUR </em>
   DEVICES
  <% end %>

  <%= link_to stream_path, :class => "btn btn-lg btn-#{params[:controller] == "streams" ? "primary" : "tesla"}" do %>
  <em> CHOOSE YOUR </em>
   DATA
  <% end %>
 
  <%= link_to jig_interface_path(3), :class => "btn btn-lg btn-#{params[:controller] == "jig" ? "primary" : "tesla"}" do %>
  <em> DESIGN YOUR </em>
   ENVIRONMENT
  <% end %>
</div>
</div>

app/views/application/home.html.erb
<div class="col-12-xs alpha">
	<!-- DESCRIPTION -->
		<h2> Illumination Aesthetics </h2>
		<p class='lead'>
			<em> 
				Exposing Light as Creative Material
			</em> 
			<address>
			  <strong>Cesar Torres</strong><br>
			  cearto@berkeley.edu <br>
			</address>
			<address>
			  <strong>Caroline Chen, Jacqueline Garcia, Ryan Kapur, Jasper O'Leary, Niraj Rao </strong><br>
			</address>
			<address>
			  <strong>Eric Paulos</strong><br>
			  paulos@berkeley.edu <br>
			</address>
			
		</p>
		<br>
		<%= link_to tool_designer_path, :class => "btn btn-primary btn-lg" do %>
			<span class="glyphicon glyphicon-edit"> </span> Illumination Design Tool
		<% end %>
		</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ELD - <%= params[:action].humanize %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- <%=params[:controller]%> -->
  <% if params[:controller] != "application" %>
	  <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
	  
	  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
  <% end %>
  
  <script type="text/javascript" src="//use.typekit.net/duw7epu.js"></script>
	<script>
		try { Typekit.load(); } catch (e) {}
	</script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
  <script type="text/javascript">
	  $(function(){
		// PREVENT BROWSER BUMP
		$(window).on('scroll', function(e){
		   scrollAmount = $(this).scrollTop();
		   if(scrollAmount < 1){
		      $(this).scrollTop(1);
		   }
		   if(scrollAmount > $(document).height() - $(window).height()){
		      $(this).scrollTop($(window).height());
		   }
		});
	})
  </script>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/"><b id='logo'>ELD </b></a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="<%= params[:action] == "home" ? "active" : "" %>">
	        	<a href="/"> Home</a>
	        </li>
	        <li class="<%= params[:action] == "designer" ? "active" : "" %>">
	        	<%= link_to "Model Generator", tool_splitter_path() %>
	        </li>
	        <li class="<%= params[:action] == "designer" ? "active" : "" %>">
	        	<%= link_to "Designer", tool_designer_path() %>
	        </li>
	        <li class="<%= params[:action] == "pipeline" ? "active" : "" %>">
	        	<%= link_to "Refraction Reference", tool_refract_path() %>
	        </li>
	        <li class="<%= params[:action] == "pipeline" ? "active" : "" %>">
	        	<%= link_to "Diffuser Molding", tool_dope_path() %>
	        </li>
	        <li class="<%= params[:action] == "pipeline" ? "active" : "" %>">
	        	<%= link_to "Layer Generator", tool_pipeline_path() %>
	        </li> 	
	       </ul>
	  
	    </div><!-- /.navbar-collapse -->
	    
	  </div><!-- /.container-fluid -->
	</nav>
	
	  <div class="container">
	  	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
	    <%= yield %>
	  </div>
	

	
<footer class="footer shadow">
  <div class="container">
    <p class="text-muted"> <a href="/"><b>ELD</b></a>
    	UC Berkeley 2015 </p>
  </div>
</footer>

</body>
</html>

app/views/layouts/full_screen.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Illumination Aesthetics - <%= params[:action].humanize %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>   
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track' => true %>
	<!--  
	<script src="https://use.typekit.net/swf3anw.js"></script>
	<script>try{Typekit.load({ async: true });}catch(e){}</script>
	-->
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">

  <style>
  body, html{
  	position: fixed;
  }
  	#shade{
  		background: #191f26;
  		color: black;
  		width: 100%;
  		height: 100%;
  		position: absolute;
  		top: 0;
  		left: 0;
  		font-size: 48pt;
  		font-weight: bold;
  		text-shadow: 1px 1px rgb(0, 0, 0, 0.1);
  		z-index: 10000000000000000;
  		/*display: table;*/
    	/*table-layout: fixed;*/
    	
	}
  	
 	#shade #bg {
 		position: relative;
		top: 50%;
		margin-top: -300px;
	}

  </style>
</head>
<body>
		<div id="shade" class="col-xs-12 text-center">
			<img id="bg" class="" src="/loading.gif">
		</div>
	  	<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
		
	 <%= yield %>

</body>
</html>

app/views/layouts/plain.html.erb
<!DOCTYPE html>
<html>
<head>
<title>2.5D - <%= params[:action].humanize %></title>
  <!--<script type="text/javascript" src="//use.typekit.net/duw7epu.js"></script>
	<script>
		try { Typekit.load(); } catch (e) {}
	</script>  -->
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

</head>
<body>
	<%= yield %>
</body>
</html>

app/views/tool/_about_modal.html.erb
<div class="modal fade" id="about" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">About ELD</h4>
      </div>
      <div class="modal-body">
        <p> Electro-Luminescent Displays<br>
        <em> Exploring Light as Interactive Material </em>
        </p>
        <br/>

        <p>
          Authored by: <br>
          Cesar Torres, Caroline Chen, Jacqueline Garcia, Ryan Kapur, Jasper O'Leary, Niraj Rao, Eric Paulos
        </p>
        <p>
          <em> &copy; UC Berkeley 2016</em>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

app/views/tool/_brush_bar.html.erb
<script type="text/javascript">
function BrushBar(container){
    this.container = container;
    this.ws = new WebStorage();
    this.toolbox = {};
    this.state = true;
    this.brush = null;
    this.init();
    paper.tool = null;

    this.hide();
  }
  BrushBar.prototype = {
    init: function(){
      var scope = this;
      $('#visibility-button').click(function(){
        scope.hide();
      });
      // BRUSH SETUP
      brushClasses = _.map($('.brush'), function(brush){
        return $(brush).attr('tool');
      });
      _.each(brushClasses, function(brush){
        // console.log(brush);
        var toolStr = "new " + brush + "(paper)";
        var tool = eval(toolStr);
        scope.toolbox[brush] = tool;
      });


      // BRUSH BEHAVIORS
      $('.brush').hover(function(){
          BrushBar.setBrush($(this), true);
        }, function(){
          if($(this).attr('active') == "active") return;
          BrushBar.setBrush($(this), false);
        });

        $('.brush').click(function(){
          $('.brush').attr('active', '');

          _.each( $('img.brush').not(this) ,function(brush){
              BrushBar.setBrush($(brush), false);
          });

          BrushBar.setBrush($(this), true);
          // DISABLE OLD BRUSH
          if(! _.isNull(scope.getCurrentBrush())){
            var oldbrush = scope.toolbox[scope.getCurrentBrush()];
            oldbrush.disable();
          }
          // ACTIVATE BRUSH
          scope.brush = $(this).attr('tool');
          var brush = scope.toolbox[scope.brush];
          brush.enable();
          console.log("Enabling", scope.brush);
        
          paper.tool = brush.tool;

          $(this).attr('active', 'active');
        });
        var scope = this;
        $('#cache-save').click(function(){
            // saveLED information
            var name =  displays[0].svgPath;
            var led_data = CanvasUtil.queryPrefix("NLED");
            var led_data = _.map(led_data, function(led){ 
              data =  {
                position: [led.position.x, led.position.y], 
                colorID: rgb2hex(led.colorID.toCanvasStyle()), 
                target: led.target
              }
              if(led.forceTarget)
                data.forceTarget = led.forceTarget;
              return data;
            });

            var key = ["led", name].join("_")
           
            console.log("STORING", led_data);
            scope.ws.set(key, JSON.stringify(led_data));
        });
        
        $('#cache-clear').click(function(){
          var leds = CanvasUtil.queryPrefix("NLED");
          _.each(leds, function(led){
            var rays = CanvasUtil.query(paper.project, {prefix: "RAY", originLight: led.id});
            CanvasUtil.call(rays, "remove");
            led.remove();
          })
          paper.view.update();
          $('#cache-save').click();
        });
        $('#cache-reload').click(function(){
          CanvasUtil.call(CanvasUtil.queryPrefix("NLED"), "remove");
          var diffs = CanvasUtil.queryPrefix('DIF');
          var name =  displays[0].svgPath;
          var key = ["led", name].join("_");
          if(scope.ws.includes(key)){
            var led_data = JSON.parse(scope.ws.get(key));
             

             console.log("FETCHING",led_data);
             _.map(led_data, function(data){
                console.log(data);
                var led =  new paper.Path.Rectangle({
                  name: "NLED: APA102C", 
                  size: new paper.Size(Ruler.mm2pts(LED_WIDTH), Ruler.mm2pts(LED_WIDTH)),
                  strokeColor: "black",
                  strokeWidth: 1, 
                  opacity: 1.0,
                  parent: CanvasUtil.queryPrefix("ELD")[0], 
                  position: paper.view.center
                });
                led.fillColor = new paper.Color(data.colorID)
                led.colorID = new paper.Color(data.colorID)
                led.position = new paper.Point(data.position)
                led.target = data.target;
                if(data.forceTarget) led.forceTarget = data.forceTarget;
                paper.tool.holder.addRays(diffs, led);
                return led;
             });  
             
             vm.update();
             paper.view.update();
          }
        });
    },
    getCurrentBrush: function(){
      return this.brush;
    },
    update: function(){
      if(_.isNull(this.brush)) return;
      this.toolbox[this.brush].update()
    },
    show: function(now){
      var scope = this;
      if(this.state) return;
      this.state = true;
      if(now){this.container.show(); return;}
      cp.show();
      this.container.animate({
        bottom: "0px",
      }, 500);
      $('#visibility-button').html('HIDE').unbind('click').click(function(){
        scope.hide();
      });
    },
    hide: function(now){
      var scope = this;
      if(!this.state) return;
      this.state = false;
      if(now){this.container.hide(); return;}
      cp.hide();
      this.container.animate({
        bottom: "-100px",
      }, 500);
      $('#visibility-button').html('SHOW').unbind('click').click(function(){
        scope.show();
      });
    }
  }
  
  BrushBar.setBrush = function(jqNode, active){
     var img = jqNode.attr('src');
     if(_.isUndefined(img)) return;
     var brushName = img.split('_');
     var isActive = active ? "Active.png" : "NonActive.png";
     brushName[2] = isActive;
     brushName = brushName.join('_');
     jqNode.attr('src', brushName);
  }

 </script>


<!-- BRUSH BAR -->
<div id="brush-bar">
<div class="task-bar">
  <!-- <button class="pull-left btn btn-xs btn-transparent"> -->
    <!-- <span class="glyphicon glyphicon-backward"> -->
  <!-- </button> -->
  <button id="cache-save" class="pull-left btn btn-xs btn-transparent">
    <span class="glyphicon glyphicon-floppy-disk">
  </button>
  <button id="cache-reload" class="pull-right btn btn-xs btn-transparent">
    <span class="glyphicon glyphicon-refresh">
  </button>
  <button id="visibility-button" class="pull-right btn btn-xs btn-transparent">
   HIDE
  </button>
  <br class="clearfix"/>
</div>
<div class="col-xs-5">
  <div id="brush-set">
    <img class="brush" tool="LEDPlacerBrush" src="/brushes/brush_CircuitBrush_NonActive.png">
    <!-- <img class="brush" tool="FillBrush" src="/brushes/brush_PaintCan_NonActive.png"> -->
    <!-- <img class="brush" tool="MagicWandBrush" src="/brushes/brush_MagicWand_NonActive.png"> -->
    <!-- <img class="brush" tool="HeatBrush" src="/brushes/brush_HeatGun_NonActive.png"> -->
    <!-- <img class="brush" tool="LinkBrush" src="/brushes/brush_LinkBrush_NonActive.png"> -->
  </div>
  <!-- SET OF TOOLS HERE -->
</div>
<div class="col-xs-4">
  <h3>Status</h3>
</div>
 <div class="col-xs-3">
  <%= render :partial => "socket_control"%>
</div>
</div>

<style>
#brush-set{
      margin-left: 20px;
    }
    .brush{
      height: 115px;
      margin: 4px 2px;
    }
    #brush-bar{
      padding: 4px 8px;
      background: blue;
      position: absolute;
      bottom: 0;
      left: 5%;
      width: 90%;
      height: 125px;
      color: #a19e99;
      text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.45);

      border-top-left-radius: 10px;
      border-top-right-radius: 10px;
      /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#3b3a38+0,181617+98 */
      background: #3b3a38; /* Old browsers */
      background: -moz-linear-gradient(top, #3b3a38 0%, #181617 98%); /* FF3.6-15 */
      background: -webkit-linear-gradient(top, #3b3a38 0%,#181617 98%); /* Chrome10-25,Safari5.1-6 */
      background: linear-gradient(to bottom, #3b3a38 0%,#181617 98%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
      filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3b3a38', endColorstr='#181617',GradientType=0 ); /* IE6-9 */


      -webkit-box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);
      -moz-box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);
      box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);

    }
      #brush-bar.task-bar{
        height: 10px;
        margin-bottom: 5px;
      }
    #send-button{
      margin: 15% 0;
    }
</style>

app/views/tool/_canvas_widget.html.erb
<script type="text/javascript">
var mainVM, mainPaper;
$(function(){
	mainPaper = paperSetup('myCanvas');
	mainPaper.name = "mainPaper";	
});
</script>

<div id="main-canvas" class="widget status">
<label class="widget-title"> CANVAS VIEW 
  <button class="btn btn-transparent btn-sm pull-right">
    <span class="glyphicon glyphicon-resize-small"></span>
  </button>
</label>
<div id="main-canvas-container">
  <canvas id="myCanvas" class="paper"></canvas>
</div>
</div>

<style type="text/css">
	#main-canvas{
		height: 100%;
	}
	#main-canvas-container{
	  position: relative;
	  height: calc(100% - 40px);
	  width: 100%;
	  overflow: hidden;
	}
	.paper{
	  background: #f5f4f0;
	  position: relative;
	  top: 0px;
	  z-index: 0;
	  cursor: pointer;
	  -webkit-box-shadow: inset 2px 4px 15px 2px rgba(0,0,0,0.2);
		-moz-box-shadow: inset 2px 4px 15px 2px rgba(0,0,0,0.2);
		box-shadow: inset 2px 4px 15px 2px rgba(0,0,0,0.2);
	}
</style>

app/views/tool/_color_palette.html.erb
<!-- color_palette.html -->
<script type="text/javascript">
  function ColorPalette(container){
    this.container = container;
    this.state = true;
    this.history = [null];
    this.idx = 0;
    this.init();
    this.hide();
  }
  ColorPalette.prototype = {
    init: function(){
      // this.hide(true);
      colors = _.range(0, 360, 30);
      _.each(colors, function(hue){
        console.log("CREATING", hue);
        var c = new paper.Color(1.0);
        c.hue = hue;
        var hex = rgb2hex(c.toCanvasStyle());
        var cDOM = $('<span class="mini-color-swatch"></span>').attr('name', hex);
        $("#color-palette").append(cDOM);
      })
      var scope = this;
      _.each($('.color-swatch'), function(swatch){
        $(swatch).css('background', $(swatch).attr('name'));
        $(swatch).click(function(){
          var clickedColor = $(swatch).attr('name');
          if(scope.getCurrentColor() != clickedColor){
            $(".color-swatch").not(this)
              .removeClass('color-swatch-active');
            $(this).addClass('color-swatch-active');
            scope.history.push(clickedColor);
            scope.idx++;
          }
        });
      });
    },
    getCurrentColor: function(){
      var color = this.history[this.idx];
      if(_.isNull(color)) color = "#FFFFFF";
      return color;
    },
    getLastColor: function(){
      lastIdx = this.idx - 1 > 0 ? this.idx - 1: 0;
      return this.history[lastIdx];
    }, 
    show: function(now){
      if(this.state) return;
      this.state = true;
      if(now){this.container.show(); return;}
      this.container.toggle("slide", { direction: "left" }, 500);
    }, 
    hide: function(now){
      if(!this.state) return;
      this.state = false;
      if(now){this.container.hide(); return;}
      this.container.toggle("slide", { direction: "left" }, 500);
    }
  }

</script>

<!-- <div id="sidebar-left">
  <div id="color-palette">
    <span class="color-swatch" name="#fe6e4b"></span>
    <span class="color-swatch" name="#eeb84b"></span>
    <span class="color-swatch" name="#6ebda7"></span>
    <span class="color-swatch" name="#00A8E1"></span>
    <span class="color-swatch" name="#FFFFFF"></span>
    <span class="color-swatch" name="#000000"></span>
  </div>
 -->

  <!--  COLOR PALETTE CODE HERE -->
   <!-- <h3>Set Colors</h3>
  <div class="input-group input-group-md">
    <span class="input-group-addon color-picker-label" id="sizing-addon1">1</span>
    <input type="color" class="form-control color-picker" value="#E74C3C">
    <span class="input-group-btn">
      <button id="button-t2-l1" class="btn btn-secondary" type="button">Send</button>
    </span>
  </div> -->
</div>

<style>
#sidebar-left{
    /* PALETTE */
    display: none;
    position: absolute;
    top: 65px;
    left: 0;
    width: 80px;
    height: 70%;
    z-index: -1;
    border-top-right-radius: 10px;
    border-bottom-right-radius: 10px;
    /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#181617+0,3b3a38+100 */
    background: #181617; /* Old browsers */
    background: -moz-linear-gradient(left, #181617 0%, #3b3a38 100%); /* FF3.6-15 */
    background: -webkit-linear-gradient(left, #181617 0%,#3b3a38 100%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(to right, #181617 0%,#3b3a38 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#181617', endColorstr='#3b3a38',GradientType=1 ); /* IE6-9 */

    -webkit-box-shadow: 5px 0px 24px 3px rgba(0,0,0,0.09);
    -moz-box-shadow: 5px 0px 24px 3px rgba(0,0,0,0.09);
    box-shadow: 5px 0px 24px 3px rgba(0,0,0,0.09);
  }

  #color-palette{
    background: #111;
    /*background: #191718;*/
    padding: 3px;
    margin: 5px;
    width: 85%;
    height: 70%;
    border-top-right-radius: 5px;
    border-bottom-right-radius: 5px;

      -webkit-box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);
    -moz-box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);
    box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);

  }
  
  .color-swatch{
    float: left;
    width: 45px;
    height: 45px;
    margin: 4px 2px 4px 8px;
    border: #444 0.5px solid;
    border-radius: 90px;


    -webkit-box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);
    -moz-box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);
    box-shadow: 0px -5px 24px 3px rgba(0,0,0,0.09);
  }
  .color-swatch-active{
    border: 2px solid #FDFDFD;
  }
</style>

app/views/tool/_stream_widget.html.erb
<script>
  $(function(){
    d3.csv("/data.csv", function(error, data) {
      data = _.map(data, function(datum){
        return _.values(datum).join(',');
      });
      data.unshift("id,type,time,voltage");
      $('#streamer').val(data.join('\n'));
    });
  });
</script>
<div id="stream" class="widget status">
  <label class="widget-title" name="stream"></label>              
  <div class="widget-body">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">
          <span class="glyphicon glyphicon-filter">
          </span>
        </button>

      </span>
    </div><!-- /input-group -->
    <br>

    <textarea id="streamer" rows="10">
      <!-- DUMMY DATA -->
      C, 0, 120, 120, 120
      C, 5, 120, 120, 120
      C, 12, 120, 120, 120
      M, 50
      C, 12, 120, 120, 120
      C, 12, 120, 120, 120
    </textarea>
  </div>
</div>